### ISSUE TITLE
Make settings persistent

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-shipyard/station#55]
At the moment there is nothing to persist the settings between sessions. We need to add something, probably a simple text file or something more advanced? Suggestions?

**Comment by Dignifiedquire** [comment]
This is needed for #29

**Comment by diasdavid** [comment]
I would say that we could use `mfs`, but since it won't be there by default until 0.4.0, a simple obj in a known location, with other config objs (like npm's one), should be good enough :)

**Comment by jbenet** [comment]
:+1: for keeping the station config on the ipfs node itself. 

one important thing to consider is that the repo in 0.4.0 gets closer to being just ipfs objects. once it is all one ipfs graph, we have a node represented fully in ipfs which means there's just encryption missing so that you can instantiate your node in any computer by just having one string (a hash + a key)

**Comment by Dignifiedquire** [comment]
Would love it to be on the ipfs node! @jbenet how close to a usable version of `mfs` and or 0.4.0 are you timewise?

**Comment by jbenet** [comment]
You can use `0.4.0` already -- just need to compile it. 

am surprised gobuilder doesn't build it, maybe there's no tag for it.

**Comment by jbenet** [comment]
i just pushed a tag for it, maybe gobuilder will build it for you.

**Comment by jbenet** [comment]
gobuilder broke more: https://gobuilder.me/github.com/ipfs/go-ipfs/cmd/ipfs/log/436733ccb7429cf9 keep an eye on https://github.com/ipfs/go-ipfs/issues/1660

**Comment by hacdias** [comment]
Which kind of settings are being talked about here? I don't think this is applicable to what we've now so it could be closed. /cc @diasdavid
